[package]
name = "quicktag"
version = "0.3.0"
edition = "2021"

[dependencies]
# General
anyhow = "1.0.75"
bytemuck = "1.14.1"
chrono = "0.4.31"
clap = { version = "4.3.11", features = ["derive"] }
env_logger = "0.10.0"
itertools = "0.12.1"
lazy_static = "1.4.0"
linked-hash-map = "0.5.6"
log = "0.4.20"
profiling = { version = "1.0.15", features = [] }
rustc-hash = "1.1.0"

# UI
eframe = { version = "0.23.0", default-features = false, features = [
    "default_fonts",
    "wayland",
    "x11",
    "persistence",
    "wgpu",
] }
egui-notify = "0.10.0"
native-dialog = "0.7.0"
opener = "0.6.1"

# Parallelism
poll-promise = "0.3.0"
rayon = "1.8.0"

# (de)serialization
base64 = "0.21.4"
bincode = "2.0.0-rc.3"
binrw = "0.12.0"
destiny-pkg = { version = "0.9.6", features = ["bincode"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.108"
vgmstream = { git = "https://github.com/cohaereo/vgmstream-rs/", version = "0.1.2" }
wav = "1.0.0"
zstd = { version = "0.13.0", features = ["zstdmt"] }

[profile.dev]
opt-level = 3
# cohae: Overflow checks are nice for some, but not for us
overflow-checks = false

# [profile.release]
# opt-level = 3
# strip = "symbols"
# lto = "fat"
# debug = 1
