# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build (nightly)

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/.md"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Nightly (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: true
      matrix:
        platform: [windows-latest]
        toolchain: [stable]
    steps:
      - uses: actions/checkout@v4

      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "rust-build"

      - name: Build
        run: cargo build --verbose --release

      - name: Copy FFmpeg DLLs
        run: cp ./lib/*.dll ./target/release/

      - name: Publish artifact
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: quicktag
          path: |
            ./target/release/*.exe
            ./target/release/*.pdb
            ./target/release/*.dll
